### ISSUE TITLE
Error: Cannot find module 'async'

### ISSUE THREAD

**Issue by dcts** [thiagozs/twitter-dl#3]
When running the example code I get the following error:

```
Error: Cannot find module 'async'
Require stack:
- /home/dcts/code/download-twitter-video/node_modules/download-progress/lib/download-progress.js
- /home/dcts/code/download-twitter-video/node_modules/twitter-dl/index.js
- /home/dcts/code/download-twitter-video/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18)
    at Object.<anonymous> (/home/dcts/code/download-twitter-video/node_modules/download-progress/lib/download-progress.js:15:13)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18)
    at Object.<anonymous> (/home/dcts/code/download-twitter-video/node_modules/twitter-dl/index.js:7:24)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18)
    at Object.<anonymous> (/home/dcts/code/download-twitter-video/index.js:3:10)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/dcts/code/download-twitter-video/node_modules/download-progress/lib/download-progress.js',
    '/home/dcts/code/download-twitter-video/node_modules/twitter-dl/index.js',
    '/home/dcts/code/download-twitter-video/index.js'
  ]
}
```

**Comment by dcts** [comment]
Fixed by running 

```
npm install async
```
